package com.curso;

public enum FuncoesEnum{

    MONITOR_JOVEM_SALA,
    MONITOR_JOVEM_EXTERNA,
    MONITOR_ADULTO_SALA,
    MONITOR_ADULTO_EXTERNA,
    MONITOR_FOLCLORE,
    COORDENADOR,
    BASE,
    LITURGIA,
    COORDENADOR_DE_FOLCLORE,
    DIRETOR_ESPIRITUAL

}